spring.profiles.active: development
---
spring:
  profiles: development

server:
  port: ${PORT:2222}

security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: account
      accessTokenUri: http://authentication-service:9999/uaa/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      jwt:
        keyValue: Test

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 12
    prefer-ip-address: true

ribbon:
  eureka:
    enabled: true
---
spring:
  profiles: docker
server:
  port: ${PORT:2222}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 12
    prefer-ip-address: true

ribbon:
  eureka:
    enabled: true
---

